apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pair-same-time-image.fullname" . }}
  labels:
    {{- include "pair-same-time-image.labels" . | nindent 4 }}
data:
  job-template.yaml: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{ include "pair-same-time-image.fullname" . }}
      labels:
        {{- include "pair-same-time-image.labels" . | nindent 8 }}
    spec:
      template:
        spec:
          volumes:
          - name: job-template
            configMap:
              name: {{ include "pair-same-time-image.fullname" . }}
          restartPolicy: {{ .Values.restartPolicy }}
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "pair-same-time-image.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - mountPath: /template
                  name: job-template
              {{- with .Values.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.envFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
