affinity: {}
args: []
env: []
envFrom: []
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: alpine
  tag: latest
imagePullSecrets: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
resources: {}
restartPolicy: OnFailure
securityContext: {}
serviceAccount:
  create: true
  name: null
tolerations: []
